/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcercaDeMiRouteImport } from './routes/acerca-de-mi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DemenciaYAlzheimerRouteImport } from './routes/demencia-y-alzheimer'
import { Route as DiabetesRouteImport } from './routes/diabetes'
import { Route as EscribirRouteImport } from './routes/escribir'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeMiRoute = AcercaDeMiRouteImport.update({
  id: '/acerca-de-mi',
  path: '/acerca-de-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DemenciaYAlzheimerRoute = DemenciaYAlzheimerRouteImport.update({
  id: '/demencia-y-alzheimer',
  path: '/demencia-y-alzheimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiabetesRoute = DiabetesRouteImport.update({
  id: '/diabetes',
  path: '/diabetes',
  getParentRoute: () => rootRouteImport,
} as any)
const EscribirRoute = EscribirRouteImport.update({
  id: '/escribir',
  path: '/escribir',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/demencia-y-alzheimer': typeof DemenciaYAlzheimerRoute
  '/diabetes': typeof DiabetesRoute
  '/escribir': typeof EscribirRoute
  '/servicios': typeof ServiciosRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/demencia-y-alzheimer': typeof DemenciaYAlzheimerRoute
  '/diabetes': typeof DiabetesRoute
  '/escribir': typeof EscribirRoute
  '/servicios': typeof ServiciosRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/demencia-y-alzheimer': typeof DemenciaYAlzheimerRoute
  '/diabetes': typeof DiabetesRoute
  '/escribir': typeof EscribirRoute
  '/servicios': typeof ServiciosRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de-mi'
    | '/auth'
    | '/blog'
    | '/contacto'
    | '/demencia-y-alzheimer'
    | '/diabetes'
    | '/escribir'
    | '/servicios'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de-mi'
    | '/auth'
    | '/blog'
    | '/contacto'
    | '/demencia-y-alzheimer'
    | '/diabetes'
    | '/escribir'
    | '/servicios'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/acerca-de-mi'
    | '/auth'
    | '/blog'
    | '/contacto'
    | '/demencia-y-alzheimer'
    | '/diabetes'
    | '/escribir'
    | '/servicios'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeMiRoute: typeof AcercaDeMiRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DemenciaYAlzheimerRoute: typeof DemenciaYAlzheimerRoute
  DiabetesRoute: typeof DiabetesRoute
  EscribirRoute: typeof EscribirRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de-mi': {
      id: '/acerca-de-mi'
      path: '/acerca-de-mi'
      fullPath: '/acerca-de-mi'
      preLoaderRoute: typeof AcercaDeMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demencia-y-alzheimer': {
      id: '/demencia-y-alzheimer'
      path: '/demencia-y-alzheimer'
      fullPath: '/demencia-y-alzheimer'
      preLoaderRoute: typeof DemenciaYAlzheimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diabetes': {
      id: '/diabetes'
      path: '/diabetes'
      fullPath: '/diabetes'
      preLoaderRoute: typeof DiabetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escribir': {
      id: '/escribir'
      path: '/escribir'
      fullPath: '/escribir'
      preLoaderRoute: typeof EscribirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeMiRoute: AcercaDeMiRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DemenciaYAlzheimerRoute: DemenciaYAlzheimerRoute,
  DiabetesRoute: DiabetesRoute,
  EscribirRoute: EscribirRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
